<template>
  <div class="dashboard-container">
    <p>fasdfasfd</p>
    <p>fasdfasfd</p>
    <p>fasdfasfd</p>
    <p>fasdfasfd</p>
    <p>fasdfasfd</p>
    <p>fasdfasfd</p>
    <p>fasdfasfd</p>
    <p>fasdfasfd</p>
    <p>fasdfasfd</p>
    <p>fasdfasfd</p>
    <p>fasdfasfd</p>
    <p>fasdfasfd</p>
    <p>fasdfasfd</p>
    <p>fasdfasfd</p>
    <p>fasdfasfd</p>
    <p>fasdfasfd</p>
    <p>fasdfasfd</p>
    <p>fasdfasfd</p>
    <p>fasdfasfd</p>
    <p>fasdfasfd</p>
    <p>fasdfasfd</p>
    <p>fasdfasfd</p>
    <p>fasdfasfd</p>
    <p>fasdfasfd</p>
    <p>fasdfasfd</p>
    <p>fasdfasfd</p>
    <p>fasdfasfd</p>
    <p>fasdfasfd</p>
    <p>fasdfasfd</p>
    <p>fasdfasfd</p>
    <p>fasdfasfd</p>
    <p>fasdfasfd</p>
    <p>fasdfasfd</p>
    <p>fasdfasfd</p>
    <p>fasdfasfd</p>
    <p>fasdfasfd</p>
    <p>fasdfasfd</p>
    <p>fasdfasfd</p>
    <p>fasdfasfd</p>
    <p>fasdfasfd</p>
    <p>fasdfasfd</p>
    <p>fasdfasfd</p>
    <p>fasdfasfd</p>
    <p>fasdfasfd</p>
    <p>fasdfasfd</p>
    <p>fasdfasfd</p>
    <p>fasdfasfd</p>
    <p>fasdfasfd</p>
    <p>fasdfasfd</p>
    <p>fasdfasfd</p>
    <p>fasdfasfd</p>
    <p>fasdfasfd</p>
    <p>fasdfasfd</p>
    <p>fasdfasfd</p>
    <p>fasdfasfd</p>
    <p>fasdfasfd</p>
    <p>fasdfasfd</p>
    <p>fasdfasfd</p>
    <p>fasdfasfd</p>
    <p>fasdfasfd</p>
    <p>fasdfasfd</p>
    <p>fasdfasfd</p>
    <p>fasdfasfd</p>
    <p>fasdfasfd</p>
    <p>fasdfasfd</p>
    <p>fasdfasfd</p>
    <p>fasdfasfd</p>
    <p>fasdfasfd</p>
    <p>fasdfasfd</p>
    <p>fasdfasfd</p>  
  </div>
</template>

<script>

export default {
  name: 'dashboard'
}
</script>